name: test github workflow
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'give repo name'
        required: true
        type: string
jobs:

  apply-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout main workflow repo
        uses: actions/checkout@v3
        with:
          path: main 
      - name: Checkout second repo
        uses: actions/checkout@v3
        with:
          repository: Boutheina-Dab/${{ inputs.repo }}
          path: ${{ inputs.repo }}
      - name: ls on second repo
        run: |
          ls -la
      - name: cat yaml file
        run: |
          cat 
      
